# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
   - job1: FirstJob
     steps:
     - bash: echo Build FirstJob
   - job2: SecondJob
     steps:
     - bash: echo Build SecondJob
 - stage: DevDeploy
   jobs:
   - job1: FirstJob
     steps:
     - bash: echo DevDeployJob
 - stage: QADeploy
   jobs:
   - job1: FirstJob
     steps:
     - bash: echo QADeployJob
 - stage: ProdDeploy
   jobs:
    - job1: FirstJob
      steps:
       - bash: echo ProdDeployJob

steps:
- script: echo Job1 Step1!
  displayName: 'Run a one-line script'


